export const siteMap: any = {
    '/login': 'login',
    '/expertregister': 'expertregister',
    '/customerregister': 'customerregister',
    '/user/studentdashboard': 'customerdashboard',
    '/user/studentdashboard/chat': 'customerchat',
    '/user/studentdashboard/search': 'customersearch',
    '/user/studentdashboard/seminar': 'customerseminar',
    '/user/studentdashboard/calendar': 'customercalendar',
    '/user/studentdashboard/joinMeeting': 'customerjoinmeeting',
    '/user/studentdashboard/profile': 'customerprofile',

    '/user/expertdashboard': 'expertdashboard',
    '/user/expertdashboard/chat': 'expertchat',
    '/user/expertdashboard/calendar': 'expertcalendar',
    '/user/expertdashboard/timeslots': 'experttimeslots',
    '/user/expertdashboard/profile': 'expertprofile',
    '/user/expertdashboard/joinMeeting': 'expertjoinmeeting',
    '/user/expertdashboard/seminar': 'expertseminar',
    '/user/expertdashboard/search': 'expertsearch',

    '/user/admindashboard': 'admindashboard',
    '/user/admindashboard/usermgmt': 'adminusermgmt',
    '/user/admindashboard/payment': 'adminpayment',
    '/user/admindashboard/chat': 'adminchat',
}