export const COUNTRY_CODES = [
  { code: '+1', country: 'US/CA', iso: 'US' },
  { code: '+44', country: 'UK', iso: 'GB' },
  { code: '+86', country: 'China', iso: 'CN' },
  { code: '+81', country: 'Japan', iso: 'JP' },
  { code: '+91', country: 'India', iso: 'IN' },
  { code: '+49', country: 'Germany', iso: 'DE' },
  { code: '+33', country: 'France', iso: 'FR' },
  { code: '+61', country: 'Australia', iso: 'AU' },
  { code: '+55', country: 'Brazil', iso: 'BR' },
  { code: '+82', country: 'Korea', iso: 'KR' },
  { code: '+65', country: 'Singapore', iso: 'SG' },
  { code: '+971', country: 'UAE', iso: 'AE' },
  { code: '+7', country: 'Russia', iso: 'RU' },
  { code: '+20', country: 'Egypt', iso: 'EG' },
  { code: '+254', country: 'Kenya', iso: 'KE' },
  { code: '+52', country: 'Mexico', iso: 'MX' },
  { code: '+54', country: 'Argentina', iso: 'AR' },
  { code: '+66', country: 'Thailand', iso: 'TH' },
  { code: '+92', country: 'Pakistan', iso: 'PK' },
  { code: '+234', country: 'Nigeria', iso: 'NG' },
];
