server {
    listen 80;
    
    # Root directory where Nginx will serve files from
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # SPA routing fallback: if the file isn't found, load index.html
        try_files $uri $uri/ /index.html;
    }
}
